name: Build and Deploy to ECS (Windows)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Windows Docker image
        run: |
          docker build -t my-app:latest .
          docker tag my-app:latest ${{ steps.login-ecr.outputs.registry }}/my-app:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/my-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ecs-cluster-name \
            --service my-app-service \
            --force-new-deployment