
services:
  kong:
    image: kong:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"   # Proxy access
      - "8001:8001"   # Admin API
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    depends_on:
      - employeewrite
      - employeeread
      - userservice
    networks:
      - kong-net

  employeewrite:
    build:
      context: ./EmployeeWriteService
    container_name: employeewriteservice
    platform: windows/amd64
    ports:
      - "9001:80"
    networks:
      - kong-net

  employeeread:
    build:
      context: ./EmployeeReadService
    container_name: employeereadservice
    platform: windows/amd64
    ports:
      - "9002:80"
    networks:
      - kong-net

  userservice:
    build:
      context: ./UserService
    container_name: userservice
    platform: windows/amd64
    ports:
      - "9003:80"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge